sudo: false
language: node_js

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      node_js: "14"
    - os: linux
      node_js: "12"
    - os: linux
      node_js: "10"
    - os: osx
      node_js: "14"
    - os: osx
      node_js: "12"
    - os: osx
      node_js: "10"
  fast_finish: true

script: yarn travis

after_success:
  - cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
  - bash <(curl -s https://codecov.io/bash) -X gcov
  - rm -rf ./coverage
